# Generated by Django 3.1.4 on 2021-07-02 17:16

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='AwardType',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('awardtype_name', models.CharField(max_length=50)),
            ],
            options={
                'verbose_name': 'Вид наград',
                'verbose_name_plural': 'Виды нарад',
            },
        ),
        migrations.CreateModel(
            name='Lpu',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code_lpu', models.IntegerField(verbose_name='Код лпу')),
                ('name_lpu', models.CharField(max_length=200, verbose_name='Наименование')),
            ],
            options={
                'verbose_name': 'ЛПУ',
                'verbose_name_plural': 'ЛПУ',
            },
        ),
        migrations.CreateModel(
            name='Post',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name_post', models.CharField(max_length=150, verbose_name='Наименование')),
            ],
            options={
                'verbose_name': 'Должность',
                'verbose_name_plural': 'Должности',
            },
        ),
        migrations.CreateModel(
            name='Doctor',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('lastname', models.CharField(max_length=100, verbose_name='Фамилия')),
                ('firstname', models.CharField(max_length=100, verbose_name='Имя')),
                ('fathername', models.CharField(max_length=100, verbose_name='Отчество')),
                ('birthday', models.DateField(verbose_name='Дата рождения')),
                ('experience_all', models.IntegerField(verbose_name='общий')),
                ('experience_branch', models.IntegerField(verbose_name='в отрасли')),
                ('experience_last', models.IntegerField(verbose_name='на последнем месте')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('lpu', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='doctors', to='awards.lpu', verbose_name='ЛПУ')),
                ('post', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='awards.post', verbose_name='Должность')),
            ],
            options={
                'verbose_name': 'Сотрудник',
                'verbose_name_plural': 'Сотрудников',
            },
        ),
        migrations.CreateModel(
            name='Award',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('incoming_num', models.IntegerField(verbose_name='Вх. №')),
                ('incoming_date', models.DateField(verbose_name='Вх. дата')),
                ('year_award', models.IntegerField(verbose_name='Год награды')),
                ('number_award', models.CharField(max_length=50, verbose_name='Номер приказа')),
                ('date_order_award', models.DateField(verbose_name='Дата приказа')),
                ('status', models.CharField(choices=[('draft', 'На расмотрении'), ('refused', 'Отклонен'), ('approved', 'Подтвержден')], max_length=10)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('doctor', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='awards.doctor', verbose_name='Сотрудник')),
                ('type_award', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='awards.awardtype', verbose_name='Тип награды')),
            ],
            options={
                'verbose_name': 'Награда',
                'verbose_name_plural': 'Награды',
            },
        ),
    ]
